name: zs-big5
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=10.0.130
  - gensim
  - jupyter
  - notebook
  - pandas
  - pingouin
  - pip
  - python=3.7
  - pytorch
  - scikit-learn
  - seaborn
  - torchvision
  - transformers
  - sentencepiece=0.1.91
